### ISSUE TITLE
Its not decrypting my file after I drag it over

### ISSUE THREAD

**Issue by iGetUploaded** [ic3w0lf22/RAMDecrypt#4]
Title says it all

**Comment by eth030** [comment]
same, i have a recent RAM version

**Comment by eth030** [comment]
okay i found the culprint, you have to go to settings and reset your encryption method and set t to Default/Standard or you will not be able to use Decrypt.exe
![grafik](https://github.com/ic3w0lf22/RAMDecrypt/assets/6024410/09457886-62eb-4816-a100-983e4c5904e7)
